#!/bin/env python

import argparse
from githubuser import GithubUser

parser = argparse.ArgumentParser(description='Demo GitHub REST API script.')
parser.add_argument('repo', nargs='?', type=str,
                    help='Repo name')
parser.add_argument('-u', '--user', dest='user',
                    help='GitHub user to inspect (default: <GitHub login>)')
parser.add_argument('-L', '--list', action='store_true',
                    help='List all repos of USER')
parser.add_argument('-b', '--branches', action='store_true',
                    help='List all branches of choosen [repo] (if none - avoiding)')
parser.add_argument('-l', '--labels', action='store_true',
                    help='List all labels attached to [repo] (if none - avoiding)')
parser.add_argument('-t', '--time', action='store_true',
                    help='Print access info for [repo] (if none - avoiding)')
parser.add_argument('-p', '--pulls', action='store_true',
                    help='List all pull request of [repo] (if none - avoiding)')
parser.add_argument('-v', '--version', action='version',
                    version='%(prog)s 0.2')

args = parser.parse_args()

# log in to GitHub and optionally store login
user1 = GithubUser()

# workaround for default value assignation
if not args.user:
    args.user = user1.login

if args.list:
    print("-L option is provided, avoiding all others")
    user1.get_repos(args.user)
    exit(0)
elif not args.repo:
    print(user1)
else:
    user1.get_repo(args.user, args.repo)
    if args.time:
        user1.get_time(args.user, args.repo)
    if args.branches:
        user1.get_branches(args.user, args.repo)
    if args.labels:
        user1.get_labels(args.user, args.repo)
    if args.pulls:
        user1.get_pulls(args.user, args.repo)
